version: "3"

services:
  gym-api-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=gymapi
      - POSTGRESQL_PASSWORD=gymapi
      - POSTGRESQL_DATABASE=gymapi
